import { createHmac } from "crypto";
import { ExecutionContext } from "@nestjs/common";
import { MonitorGuard } from "../../../../../external-integrations/nestjs/src/monitor.guard";
import { validateMonitorRequest } from "../../../../../external-integrations/nextjs/lib/validate-monitor-request";
import { HmacSignerService } from "../../common/hmac-signer.service";

/**
 * Cross-framework consistency tests.
 *
 * Verifies that the HMAC signatures generated by HealthPanel's HmacSignerService
 * are correctly validated by ALL external integrations (NestJS, Next.js, and
 * by extension Laravel which uses the same algorithm).
 */
describe("Cross-framework HMAC consistency", () => {
  const API_KEY = "cross-test-key";
  const SECRET = "cross-test-secret-64chars-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
  let signer: HmacSignerService;

  beforeAll(() => {
    signer = new HmacSignerService();
  });

  beforeEach(() => {
    process.env["MONITOR_API_KEY"] = API_KEY;
    process.env["MONITOR_SECRET"] = SECRET;
  });

  afterEach(() => {
    delete process.env["MONITOR_API_KEY"];
    delete process.env["MONITOR_SECRET"];
  });

  it("HmacSignerService sign → NestJS MonitorGuard validates", () => {
    const headers = signer.sign(API_KEY, SECRET, "GET", "/health");
    const guard = new MonitorGuard();

    const ctx = {
      switchToHttp: () => ({
        getRequest: () => ({
          headers,
          method: "GET",
          originalUrl: "/health",
        }),
      }),
    } as unknown as ExecutionContext;

    expect(guard.canActivate(ctx)).toBe(true);
  });

  it("HmacSignerService sign → Next.js validateMonitorRequest validates", () => {
    const signed = signer.sign(API_KEY, SECRET, "GET", "/api/health");

    const headers = new Headers();
    headers.set("x-monitor-key", signed["x-monitor-key"]);
    headers.set("x-monitor-timestamp", signed["x-monitor-timestamp"]);
    headers.set("x-monitor-signature", signed["x-monitor-signature"]);

    const result = validateMonitorRequest(headers, "GET", "/api/health");
    expect(result).toEqual({ valid: true });
  });

  it("HmacSignerService verify → validates same format as external integrations", () => {
    // Sign with the signer
    const signed = signer.sign(API_KEY, SECRET, "GET", "/logs");

    // The verify method on HmacSignerService should also validate the signature
    const isValid = signer.verify(
      SECRET,
      "GET",
      "/logs",
      signed["x-monitor-timestamp"],
      signed["x-monitor-signature"],
    );

    expect(isValid).toBe(true);
  });

  it("all implementations use the same payload format: {timestamp}:{METHOD}:{path}", () => {
    const timestamp = String(Date.now());
    const method = "GET";
    const path = "/health";

    // HealthPanel API signing (from HmacSignerService)
    const payload = `${timestamp}:${method.toUpperCase()}:${path}`;
    const expected = createHmac("sha256", SECRET).update(payload).digest("hex");

    // Verify using HmacSignerService.verify
    expect(signer.verify(SECRET, method, path, timestamp, expected)).toBe(true);

    // Verify using NestJS MonitorGuard
    const guard = new MonitorGuard();
    const ctx = {
      switchToHttp: () => ({
        getRequest: () => ({
          headers: {
            "x-monitor-key": API_KEY,
            "x-monitor-timestamp": timestamp,
            "x-monitor-signature": expected,
          },
          method: "GET",
          originalUrl: "/health",
        }),
      }),
    } as unknown as ExecutionContext;
    expect(guard.canActivate(ctx)).toBe(true);

    // Verify using Next.js validateMonitorRequest
    const h = new Headers();
    h.set("x-monitor-key", API_KEY);
    h.set("x-monitor-timestamp", timestamp);
    h.set("x-monitor-signature", expected);
    expect(validateMonitorRequest(h, method, path)).toEqual({ valid: true });
  });

  it("all implementations reject a tampered signature consistently", () => {
    const timestamp = String(Date.now());
    const tampered = "b".repeat(64);

    // HmacSignerService.verify rejects
    expect(signer.verify(SECRET, "GET", "/health", timestamp, tampered)).toBe(
      false,
    );

    // NestJS MonitorGuard rejects
    const guard = new MonitorGuard();
    const ctx = {
      switchToHttp: () => ({
        getRequest: () => ({
          headers: {
            "x-monitor-key": API_KEY,
            "x-monitor-timestamp": timestamp,
            "x-monitor-signature": tampered,
          },
          method: "GET",
          originalUrl: "/health",
        }),
      }),
    } as unknown as ExecutionContext;
    expect(() => guard.canActivate(ctx)).toThrow();

    // Next.js validateMonitorRequest rejects
    const h = new Headers();
    h.set("x-monitor-key", API_KEY);
    h.set("x-monitor-timestamp", timestamp);
    h.set("x-monitor-signature", tampered);
    const result = validateMonitorRequest(h, "GET", "/health");
    expect(result).toEqual({
      valid: false,
      error: "Invalid monitor signature",
    });
  });
});
